[package]
name = "kramwriter-os"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.11"                # Downgrade this to match rpi_memory_display
rpi_memory_display = "0.1.2"
embedded-graphics = "0.8"
anyhow = "1.0"
ropey = "1.6"
termion = "2.0"
chrono = "0.4"
parking_lot = "0.12"